- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Amber
  - Atlas
  - Bagel
  - Box
  - Cluster
  #- Cog # Goobstation - cog is broken
  - Core
  - Elkridge
  - Fland
  - Marathon
  - Meta
  - Oasis
  - Omega
  - Origin
  - Saltern
  - Packed
  #- Reach # funkystation - operation revive lrp
  #- roid_outpost SM setup bad, evac dock always extended, more and stuff
  #- Train - Train is pain
  - FlandHighPop
  - OasisHighPop
  #- Barratry # Harmony - Barratry 2.0 - Funkystation - Barratrauma
  - Kettle
